export default {
  SWITCH_MENU: "SWITCH_MENU",
  OPEN_MENU: "OPEN_MENU",
  OPEN_ACCOUNT: "OPEN_ACCOUNT",
  TODO_BUTTONS: "TODO_BUTTONS",
  BOTTOM_TABS: "BOTTOM_TABS",
  SIDE_MENUS: "SIDE_MENUS",
  WIDGET_TABS: "WIDGET_TABS"
};
